### ISSUE TITLE
Compile on Debian 10 buster

### ISSUE THREAD

**Issue by ik0** [pdf2htmlEX/pdf2htmlEX#56]
Hello,

I'm trying to build pdf2htmlEX on debian 10 with poppler 0.71 . Which version (branch/tag?) to try ? I've tried for Ubuntu 18.10 (for poppler 0.68) and 19.04 (for poppler 0.74), but both failed compiling with different errors.

**Comment by GMolini** [comment]
You should try poppler version 0.81 and fontforge tag 20170731.

To install poppler:

```
apt-get install pkg-config fontconfig libfontconfig1-dev libjpeg-dev libtiff5 libtiff5-dev libnss3 libnss3-dev libcairo2 libcairo2-dev cmake libopenjp2-7 libopenjp2-7-dev 

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_UNSTABLE_API_ABI_HEADERS=ON ..
make
sudo make install
```
to install fontforge:

```
apt-get install libpango1.0-0 libpango1.0-dev libxml2 libxml2-dev libspiro-dev libgif-dev
git clone --depth 1 --single-branch --branch 20170731 https://github.com/fontforge/fontforge.git
cd fontforge/
git checkout tags/20170731
./bootstrap
./configure --without-x
make
make install
```

**Comment by ik0** [comment]
Hi, Guillermo,

thanks for reply. I've compiled poppler 0.81 and fontforge. How to tell pdf2htmlEX to use them in non standard path ? I do not want to overwrite my system libraries before I test everything .

**Comment by ViliusSutkus89** [comment]
Hey ik0,

This is a two part problem.

First part is installing to a different prefix.
CMake builds take INSTALL_PREFIX argument. For Poppler it will be
```bash
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/home/ik0/pdf2htmlEX_and_deps -DCMAKE_BUILD_TYPE=Release -DENABLE_UNSTABLE_API_ABI_HEADERS=ON ..
make
make install
```

Autotools takes --prefix argument, so you can
```bash
./configure --prefix=/home/ik0/pdf2htmlEX_and_deps
make
make install
```

Second part is telling pdf2htmlEX to consume libraries from /home/ik0/pdf2htmlEX_and_deps and
Most libraries produce either pkg-config.pc or CMake find_package configs.
The former available in /usr/lib/pkgconfig, the latter in /usr/lib/cmake.

To find these libraries pdf2htmlEX uses pkg_check_modules, which internally uses pkg-config,
so that's the only one that we need to worry about right now.

First verify that you can find them manually. 
pkg-config accepts PKG_CONFIG_PATH environment variable to tell it where it should look for .pc files first, before trying /usr/lib/pkgconfig . If I recall correctly one of these dependencies is installed to lib, other is to lib64, so we need to pass both.

```bash
PKG_CONFIG_PATH=/home/ik0/pdf2htmlEX_and_deps/lib/pkgconfig:/home/ik0/pdf2htmlEX_and_deps/lib64/pkgconfig pkg-config --cflags poppler libfontforge
```

Once you know that they're both installed "correctly", you can compile pdf2htmlEX with them
```bash
cd pdf2htmlEX_sources
mkdir build
cd build
PKG_CONFIG_PATH=/home/ik0/pdf2htmlEX_and_deps/lib/pkgconfig:/home/ik0/pdf2htmlEX_and_deps/lib64/pkgconfig cmake -DCMAKE_INSTALL_PREFIX=/home/ik0/pdf2htmlEX_and_deps ..
make
```

At this point you may be greeted by an error, which tells you that some header from poppler can't find "poppler/GfxState.h". Poppler's pkgconfig.pc file defines it's include path as /home/ik0/pdf2htmlEX_and_deps/include/poppler/ and this requested file would look like /home/ik0/pdf2htmlEX_and_deps/include/poppler/poppler/GfxState.h

Edit Poppler's pkgconfig.pc ( /home/ik0/pdf2htmlEX_and_deps/lib64/pkgconfig/poppler.pc ), so it includes the root include dir too.
```
CFlags: -I${includedir}/poppler
```
becomes
```
CFlags: -I${includedir}/poppler -I${includedir}
```

Try buildinging pdf2htmlEX again
```bash
cd pdf2htmlEX_sources
mkdir build
cd build
PKG_CONFIG_PATH=/home/ik0/pdf2htmlEX_and_deps/lib/pkgconfig:/home/ik0/pdf2htmlEX_and_deps/lib64/pkgconfig cmake -DCMAKE_INSTALL_PREFIX=/home/ik0/pdf2htmlEX_and_deps ..
make
make install
```

Try running the newly installed pdf2htmlEX
```bash
/home/ik0/pdf2htmlEX_and_deps/bin/pdf2htmlEX
```

You might get an error complaining about libpoppler.so not being found.
```bash
LD_LIBRARY_PATH=/home/ik0/pdf2htmlEX_and_deps/lib:/home/ik0/pdf2htmlEX_and_deps/lib64 /home/ik0/pdf2htmlEX_and_deps/bin/pdf2htmlEX
```

**Comment by ik0** [comment]
Hey Guillermo and Vilius

thanks a lot ! That should be written in some Howto or Wiki. Very useful !

a little details: i did not get error about "poppler/GfxState.h" . I've installed poppler in /usr/local/poppler-0.81 and add path to file in /etc/ld.so.conf.d/ so everyone could start pdf2htmlEX without adding LD_LIBRARY_PATH every time.
