### ISSUE TITLE
Installation in Alpine.

### ISSUE THREAD

**Issue by NishealJ** [pdf2htmlEX/pdf2htmlEX#59]
Hi,
How can I install this in Alpine Linux?
The docker image is out of date.

**Comment by Rockstar04** [comment]
Apline is not currently supported, if you get it to build feel free to open a pull request.

I am unaware of ANY docker images that are a part of this organization, we are still in the process of setting up the DockerHub org.

**Comment by stephengaito** [comment]
@NishealJ the docker image https://hub.docker.com/r/stephengaito/pdf2htmlex is up todate as of 6 hours ago. (It uses poppler-0.89.0 released last month, as well as fontforge 20200314 )

I am (this weekend) doing final testing of my development repo before I issue a pull request to pull my updates into the main pdh2htmlEX/pdf2htmlEX repository.

As part of this pull request, https://hub.docker.com/r/pdf2htmlEX/pdf2htmlex will start working.

I am also working on updating the pdf2htmlEX website and wiki to hopefully point out the changes.

I hope this helps.

As @Rockstar04 says, this is not supported on Alpine as the poppler and fontforge dependencies will probably pull in enough to warrant being simply built on Ubuntu's smallest base image.

**Comment by NishealJ** [comment]
Thanks @stephengaito, I'll take a look.

**Comment by stephengaito** [comment]
@NishealJ 

As you should be able to see... the newest release does now have an [Docker image based upon Alpine Linux 3.12](https://hub.docker.com/r/pdf2htmlex/pdf2htmlex).

While making the latest release I learned enough about Alpine Linux to create build scripts for Alpine.

However, while definitely being smaller than the Ubuntu docker images, be warned that my current attempt at an Alpine based docker image seems to be using the native `iconv` rather than the more developed `gnu-libiconv`... as such I know that it will fail to render some fonts. See the note at the bottom of the [Download Docker Image wiki page](https://github.com/pdf2htmlEX/pdf2htmlEX/wiki/Download-Docker-Image).

If you have more experience with creating Alpine Docker Images and you can fix my [createDockerAlpineImageFromTarFile build script](https://github.com/pdf2htmlEX/pdf2htmlEX/blob/master/buildScripts/createDockerAlpineImageFromTarFile), any help would be welcomed!

Please try this new version and let me know if you have any trouble.

Regards,
Stephen Gaito

**Comment by NishealJ** [comment]
Great work @stephengaito :),

where can I see the build scripts for the docker image? the docker-compose.yml file?

**Comment by stephengaito** [comment]
@NishealJ ,

Alas, because of how I automate my builds, the "dockerfile" is currently embedded *inside* my build scripts. Have a look in [ pdf2htmlEX/buildScripts/createDockerAlpineImageFromTarFile ](https://github.com/pdf2htmlEX/pdf2htmlEX/blob/master/buildScripts/createDockerAlpineImageFromTarFile) lines 53-69.

In particular:

```
cat > Dockerfile <<DOCKERFILE_HERE_DOC
FROM $DOCKER_FROM
COPY ./$ALPINE_NAME.* /root/
WORKDIR /root
RUN chmod a+x $ALPINE_NAME.install && \
  ./$ALPINE_NAME.install
  
# make the /pdf directory the default working directory for any run of 
# pdf2htmlEX 
#
WORKDIR /pdf
ENTRYPOINT ["$PDF2HTMLEX_PREFIX/bin/pdf2htmlEX"]
DOCKERFILE_HERE_DOC
```
You will notice that I build the docker file from an alpine tar file (pdf2htmlEX-0.18.8.rc1-master-20200630-alpine-3.12.0-x86_64.tar.gz) and its associated install script (which I meant to release but seem to have forgotten to add it to the upload see issue: #75 ). 

Again because I currently build *inside* a docker/podman container (so I have complete control over installed packages), I have to break the docker image creation into two parts (since *docker* can not be used inside of docker in the namespaces mode).  So in the first part I create a pair of tar file and install script, which are used in the second part to actually build the alpine docker image (while *outside* the docker container used to build the software).

I am currently looking at ways to go back to building inside KVM machines.... (alas a long story.... ) Using KVM machines again will simplify the build scripts....
